### PR TITLE
Realtime: Fix namespace issue on some PHP versions

### LINKED ISSUE #1321: mgp25/instagram-php/src/Realtime.php on line 7
mgp25/instagram-api version dev-master
error in realtimeClient.php ->
Fatal error: Cannot use InstagramAPI\Realtime\Client as Client because the name is already in use in /Applications/XAMPP/xamppfiles/htdocs/mnmn/vendor/mgp25/instagram-php/src/Realtime.php on line 7

### PR DESCRIPTION
**Pull request by valga**
Fixes #1321.

### CODE REVIEW

File: src/Realtime.php [hunk 1]
```diff
@@ -4,8 +4,7 @@
 
 use Evenement\EventEmitterInterface;
 use Evenement\EventEmitterTrait;
-use InstagramAPI\Realtime\Client;
-use InstagramAPI\Realtime\Event;
```
Comment (mgp25) [inline src/Realtime.php]: You have removed `use InstagramAPI\Realtime\Event;`

Is that okay?

Comment (valga) [inline src/Realtime.php]: Yes, it is ok, because it was unused `use` statement.
